### ISSUE TITLE
multiple account scan stop

### ISSUE THREAD

**Issue by agita88** [mchristopher/PokemonGo-DesktopMap#799] opened 2016-08-10 00:25 UTC
i made a few more accounts to scan with and it seems i can only do 3 accounts at a time. Is this the limit or is there any other reason the scan stop. When it stops and i move the marker a bit it start again but then it stops scanning on another account

**Comment by NickIxo** [comment] 2016-08-10 02:06
Your description of the problem is a bit limited, but if this may help:

I have found in my experience with scanning with 4, that sometimes one of the 4 maps ignores my marker and will only scan the location of the GPS coordinates (regardless of any moved marker).

Thus i must move 2 of my instances to the same spot, to see which one of them actually works, because the other one will stop scanning at the marker and only scan at the pre-selected location.
Let me know if that does anything for you.

**Comment by ThunderVamp9** [comment] 2016-08-10 04:11
I have the same problem as agita88.

I have 5 accounts, all activated, all different email addresses and usernames obviously, all signed into app and accepted TOS, all caught their starter.

I can start 3 of them just fine, but when I start the 4th or 5th, I get an EADDRINUSE error and that one will show my marker at the place of the 3rd one I started. If I move it, the third one stops working.

**Comment by ThunderVamp9** [comment] 2016-08-10 04:55
This may be due to the system trying to use a port number thatis already in use by my system. Can we change what ports the map is using?

**Comment by tinarazzburton** [comment] 2016-08-10 07:51
Only 3 of mine scan as well.  It would be nice to have some kind of support to enter in multiple accounts into one duplicate of the app running.

**Comment by Shogunz1** [comment] 2016-08-10 12:44
You have to literally enter into the game in that account and accept the TOS in order for it to be operational in the program. Just go in do the tututorial, pick squirtle, because he's the best, and back out.

**Comment by ThunderVamp9** [comment] 2016-08-10 12:59
As mentioned above:

"I have 5 accounts, all activated, all different email addresses and usernames obviously, all signed into app and accepted TOS, all caught their starter."

**Comment by MrAwesomers** [comment] 2016-08-11 00:58
To be honest, I was using 6 accounts before the API change, now I'm using 3. None of them have accepted anything except the confirmation email. None of them even chose a starter pokemon.

**Comment by NickIxo** [comment] 2016-08-11 02:06
Yes accounts created prior to the API change are immune to this. my original 4 accounts are in the same boat.

**Comment by ThunderVamp9** [comment] 2016-08-11 03:32
I set a range of IP's to be forwarded in my router, set up a desktop shorcut for each instance I want and then added --port 80xx to each shortcut, with the port number being different for each one. That has allowed me to run all of the instances now, so it definitely had to do with port numbers in use already.

**Comment by Sigmarion** [comment] 2016-08-12 07:58
@ThunderVamp9 can u please tell how to change the port numbers?

**Closed** 2016-09-02 07:57 UTC
