### ISSUE TITLE
Lured Pokemons

### ISSUE THREAD

**Issue by legendz97** [mchristopher/PokemonGo-DesktopMap#1223] opened 2016-09-14 00:19 UTC
How do I show lured pokemons?

**Comment by RMPPARTS** [comment] 2016-09-14 14:44
I was wondering the same thing,  Does anyone know if this can be done?

**Comment by ultimate2106** [comment] 2016-09-14 21:59
It's not implemented yet I guess

**Comment by AVellucci** [comment] 2016-09-16 16:14
Duplicate of #1222

**Closed by AVellucci** 2016-09-16 16:14 UTC
Labels: Duplicate
