### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Shinoby1992** [mchristopher/PokemonGo-DesktopMap#95] opened 2016-07-21 19:57 UTC
new release on mac OS X got me this error:

Uncaught Exception:
Error: This socket is closed
    at Socket._writeGeneric (net.js:672:19)
    at Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:650:40)
    at Timeout._onTimeout (/path/Pokemon GO Live Map.app/Contents/Resources/app/main.js:270:21)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

**Comment by mchristopher** [comment] 2016-07-21 20:17
Duplicate of #96

**Closed by mchristopher** 2016-07-21 20:17 UTC
Labels: duplicate
