### ISSUE TITLE
no pokemon

### ISSUE THREAD

**Issue by pocketq10** [mchristopher/PokemonGo-DesktopMap#1286] opened 2016-10-06 13:14 UTC
yep same issue here i guess the new update they did prevent scanning :( hope christopher fixes this

**Comment by Thefinder109** [comment] 2016-10-06 13:33
I'm seeing the same issue.

**Comment by redwizard42** [comment] 2016-10-06 13:36
Same experience here.

**Comment by secondhandnudes** [comment] 2016-10-06 13:40
I woke up this morning and all scanning had stopped around 12:30 AM EST; I had previously logged into all my accounts and gone through the CAPTCHA, and then tried it with a couple more this morning and saw the CAPTCHA again. Except this time, after that, there was a huge warning message that essentially said "your account has been flagged as likely for cheating and could be banned at any time". 

But, tried logging back in and everything is running normally now. Can't imagine it's going to last long though.

**Comment by Nicolas469** [comment] 2016-10-06 13:53
Same issue =(

**Comment by infernusdomoso** [comment] 2016-10-06 14:18
The API now issues a captcha that has to be solved or your account shows nothing on scans. Until the pgoapi is updated to account for that, theres not much that can be done. I'm working on something on the backend, but not sure how feasable it is to get it ported over.

**Comment by pocketq10** [comment] 2016-10-06 14:42
good luck @infernusdomoso hope u get great results!

**Comment by Nonkel** [comment] 2016-10-06 18:53
We need an updated version...I cant live without my scanner! ;-)

**Comment by johnnylingo** [comment] 2016-10-07 00:04
Niantic needs to let us play the game.

**Comment by nikola987** [comment] 2016-10-07 05:40
Can this scanner display the captcha so I can solve it? :)

**Comment by Nicolas469** [comment] 2016-10-07 10:02
Where can I find the CAPTCHA to solve ? I don't have to solve one when I log with my google account...

**Comment by fusenuk** [comment] 2016-10-07 11:52
You should see the captcha immediately when you sign into the pokemon account on a device, clicking I am not a robot and then solving the picture quiz will get the account working again temporarily until it's flagged as a bot again and another captcha appears.

There current api/this program won't show you that the captcha is needed it'll simply stop showing any pokemon/gym/lure updates.

**Comment by Thefinder109** [comment] 2016-10-07 12:11
Using the account to login and solving the captcha worked for me.

**Comment by Nonkel** [comment] 2016-10-07 13:41
The captcha will return after a few hours/a day or so.... it's only a temporary fix, and quite annoying when you got 10 accounts or even more...

**Comment by ManiacDC** [comment] 2016-10-07 14:29
Duplicate of issues #1282

**Comment by Nonkel** [comment] 2016-10-08 11:03
After manually doing the captcha, my accounts now are suspended even so. Displays a message on startup, can't do anything to even switch to a different account. Thank god Im using my ipad for this sh*t...

**Closed** 2022-04-25 18:09 UTC
