### ISSUE TITLE
Java Error / Nothing on Map

### ISSUE THREAD

**Issue by Shunryu34** [mchristopher/PokemonGo-DesktopMap#630] opened 2016-08-04 16:27 UTC
![sans titre](https://cloud.githubusercontent.com/assets/20843355/17409799/5616ec56-5a36-11e6-9fde-39435cddf5e9.jpg)

Sorry to open this again, but i didn't find any solutions in the previews issues...

Any idea ?

**Comment by Shunryu34** [comment] 2016-08-04 16:28
I have enabled all API also...

**Comment by khloro** [comment] 2016-08-04 16:34
Same here and download latest Java

**Comment by jasonlohk** [comment] 2016-08-04 16:37
same issue

**Comment by MacDogg** [comment] 2016-08-04 16:39
I'm sorry, but why are you trying to use the app right now?

**Comment by faccinho** [comment] 2016-08-04 16:49
Well, I get the same error so I've updated my java (that was in x86 instead of x64, the version of my computer), after that start to appear some empty green circles, this is caused for the API changed by Niantic (i guess); anyway, still giving me that java script error, but I read in this forum that is a common thing and doesn't changes the map.

**Comment by doness** [comment] 2016-08-04 16:50
\Well, Niantic has change API.. so all doesn't work...

**Comment by pcecere** [comment] 2016-08-04 16:52
the application doesnt work, but this is something that has been happening before ... you can ignore the error, and it will work anyway ... it's just annoying. i didn't have time to check why it's happening. 
but dont try the application for now, because it doesnt work at all.

**Comment by khloro** [comment] 2016-08-04 17:09
I  understand the app is not working but the Java issue is none related to the Niantic issue

**Comment by khloro** [comment] 2016-08-04 17:10
[https://drive.google.com/file/d/0BxEukpGRh3dkUXF4bEM0cDc3V1U/view?usp=sharing](url)

**Comment by HUN73R13** [comment] 2016-08-04 17:48
some of the error messages you're getting is probably caused by unhandled connection errors. I used to get these errors if I didn't run a vpn app or a proxy, since I live in Syria and we are blocked (no data recieved) so atm we should NOT report any issue until we have a working API connection and then we build on that.

**Comment by dnsBlah** [comment] 2016-08-04 18:41
brainless... someone close the issue

**Closed** 2016-09-02 07:57 UTC
