### ISSUE TITLE
Timer Not Counting Down Correctly: Example Shown. Removed Pokemon Return To Map After Refresh Or Reload. 

### ISSUE THREAD

**Issue by Tonikane** [mchristopher/PokemonGo-DesktopMap#892] opened 2016-08-13 16:53 UTC
Pokemon count down as normal but on reaching Zero or Expired they stay on the map and have this type of data attached. Have removed them individually but they return after map is refreshed or reloaded. Thank You .. Great Work Though, Love It :8ball: 
Ponyta - #77 (Rare) - FIRE
**Disappears at 22:56:22 574h08m18s)**
Location: -32.523135, 115.7472107
Exclude   Notify   Remove   Get directions

**Comment by conklin75** [comment] 2016-08-13 17:18
Same issue here

**Comment by illostos** [comment] 2016-08-13 17:24
Sams here

**Comment by pill0ws** [comment] 2016-08-13 17:55
I find the shared despawn timer interesting. When you account for timezones, all of these timeres show exactly the same despawn timmer. Mine show "Despawn at 09:56:22 (UTC-06:00 Central Time)"

**Comment by luW33Dgi** [comment] 2016-08-13 18:28
Same same. Interesting to note, for every instance of a timed-out pokemon on my map, there is a second pokemon directly underneath the timed out one that is unselectable, but there nonetheless.

**Comment by Anklosaur** [comment] 2016-08-13 20:42
Duplicate of #883 which is a duplicate of #881 which is a duplicate of #880. Issue is being worked on here: https://github.com/PokemonGoMap/PokemonGo-Map Specifically here: https://github.com/PokemonGoMap/PokemonGo-Map/pull/572

**Closed** 2016-09-02 07:57 UTC
