### ISSUE TITLE
"Oops! Something went wrong" Loading Map Error (Help)

### ISSUE THREAD

**Issue by livingtatted** [mchristopher/PokemonGo-DesktopMap#313] opened 2016-07-27 13:34 UTC
Soon as I sign in my google account and the map starts to load this pops up.

<img width="1440" alt="screen shot 2016-07-27 at 9 31 39 am" src="https://cloud.githubusercontent.com/assets/20582970/17176999/388eeeea-53dd-11e6-8f2a-f4dfa78c3261.png">

**Comment by zombou** [comment] 2016-07-27 17:07
Check my post here: #320 That helped for me.

**Comment by livingtatted** [comment] 2016-07-29 20:29
@zombou I followed the steps but my API was already enabled to there's something else wrong I hope this can help.

<img width="1440" alt="screen shot 2016-07-29 at 4 27 43 pm" src="https://cloud.githubusercontent.com/assets/20582970/17262488/9dbb326a-55a9-11e6-9b27-abb0a83088f0.png">

**Comment by AVellucci** [comment] 2016-08-17 16:59
Duplicate of #274

**Closed by AVellucci** 2016-08-17 16:59 UTC
