### ISSUE TITLE
Lures only last 2minutes.

### ISSUE THREAD

**Issue by 23ttfe3fa** [mchristopher/PokemonGo-DesktopMap#112] opened 2016-07-22 05:11 UTC
Lures always expire after 2ish minutes, When they actually haven't expired, They come back and then have another 2 minutes to expire.

Until they actually expire then there gone making the entire point of showing the expire time useless I dunno if there is a quick fix for this?

**Comment by andrewda** [comment] 2016-07-22 07:53
This has been noted before. The issue is that what Niantic returns to us as `lure_expiration` is really just a suggestion of when to recheck to see if the lure has expired. If not, it will give us a new `lure_expiration` which will last another 2 minutes. Why they do it this way, I have no idea. I'm working with some guys ATM to come up with a potential "fix".

**Comment by 23ttfe3fa** [comment] 2016-07-22 08:00
If you can't get the data for the correct time, You could possibly find when the first check was initiated and time it off then. Whatever the solution glad to hear it's been worked on because the 2min timer adds no value to the user apart from knowing there is a lure there.

**Comment by andrewda** [comment] 2016-07-22 08:18
@23ttfe3fa This is indeed what we were thinking. Niantic actually makes this insanely easy and provides us with a `last_updated` (or something, I forget exactly) parameter, which I can only assume means the last time a Lure was deployed. We could do something like:

```
30 mins - (current_time - last_updated) = remaining time
```

I'm going to add this to PokemonGo-Map tomorrow, and hopefully we can get it merged in here shortly after.

**Comment by 23ttfe3fa** [comment] 2016-07-23 13:01
I dunno whats changed in 0.1.0 but lures still seem to be buggy

Sometimes the lures say over 30 minutes, Sometimes when i refresh the time left on lure increases

This is the main reason I have this program because no lures in my vicinity and I can't really just go out looking for lures 24/7 just trying to make sure the issues with it are known don't want this to go under the radar to spawn locations (plenty of other places to do that, what makes this special is lure markers)

**Closed** 2016-08-16 16:03 UTC
