### ISSUE TITLE
JS error in version .0.8 on login.

### ISSUE THREAD

**Issue by Kairnth** [mchristopher/PokemonGo-DesktopMap#97] opened 2016-07-21 20:00 UTC
![2016-07-21 13_59_03-issues mchristopher_pokemongo-desktopmap github](https://cloud.githubusercontent.com/assets/11773720/17036879/6852b166-4f4b-11e6-80ee-21eb94d1126b.png)

Attached is a copy of the JS error I get every time I try to login in version .0.8. Other versions have all worked fine.

Running Windows 10.

**Comment by gilbarshlomo** [comment] 2016-07-21 20:04
same to me.

**Comment by Mr10001** [comment] 2016-07-21 20:10
same here as well

**Comment by poekrel** [comment] 2016-07-21 20:14
I have the same error as well.

**Comment by Mr10001** [comment] 2016-07-21 20:15
Could this be firewall related?

**Comment by mchristopher** [comment] 2016-07-21 20:15
Duplicate of #96

**Closed by mchristopher** 2016-07-21 20:15 UTC
Labels: duplicate
