### ISSUE TITLE
Pokemon expiry time

### ISSUE THREAD

**Issue by SturgBoy** [mchristopher/PokemonGo-DesktopMap#898] opened 2016-08-13 22:29 UTC
got multiple clumps of pokemon that expire in 586 hours, is there anyway to manually remove them?

**Comment by LePhantom** [comment] 2016-08-14 00:33
Yes. Click in the pokemon, than click "Remove"

**Comment by PureMassacre** [comment] 2016-08-14 09:10
I forget to that and when I get back on I get excited then realise it expired hours ago.

**Comment by SturgBoy** [comment] 2016-08-14 11:56
Clicking remove works but more keep appearing, guessing this is a problem in the coding perhaps?

**Comment by Anklosaur** [comment] 2016-08-14 19:47
Duplicate of #892 which is a duplicate of #883 which is a duplicate of #881 which is a duplicate of #880. Issue is being worked on here: https://github.com/PokemonGoMap/PokemonGo-Map Specifically here: https://github.com/PokemonGoMap/PokemonGo-Map/pull/572

**Closed** 2016-09-02 07:57 UTC
