### ISSUE TITLE
Zombie Processes & Memory Leaks

### ISSUE THREAD

**Issue by bryanhelmig** [mchristopher/PokemonGo-DesktopMap#13] opened 2016-07-20 18:24 UTC
If you close the app - the Python thread continues to run in the background. Definitely an issue with the packaging. Process manager will show this. (OS X specifically).

Also, a leak means it will eventually eat up gigabytes of data. That could be the underlying PoGo API library's fault.

**Comment by ilikesomething** [comment] 2016-07-20 18:49
Possible duplicate of #6

**Comment by xan0v** [comment] 2016-07-20 19:01
Can confirm this on Windows as well - Python process isn't killed and continues to run.

**Comment by Ruined1** [comment] 2016-07-20 20:17
Same windows 10 x64 bit. This needs fixed ASAP and should be marked important.

**Comment by mchristopher** [comment] 2016-07-20 20:22
Yeah, this has been fixed in 0.0.3. I'm going to close it for now. Please open a new issue if the problem still exists.

**Closed by mchristopher** 2016-07-20 20:22 UTC

**Comment by bryanhelmig** [comment] 2016-07-20 23:24
Confirmed no more Zombies. :-)
