### ISSUE TITLE
Anyway to initiate a 'Refresh' while simply viewing the "Mobile" ngrok.io view

### ISSUE THREAD

**Issue by jameson167** [mchristopher/PokemonGo-DesktopMap#89] opened 2016-07-21 17:08 UTC
Thanks so much for these quick releases. Every version has been adding more and more useful features.

The map seems to update fine on my computer but when I leave my home and view the ngrok.io view of the map, it stops updating unless I remotely control my computer and restart the app. Is this because the App is going into some kind of "standby" when the computer isn't in use and stops refreshing? Is there anyways to initiate a refresh while remote using Mobile besides remote desktop connection.

**Comment by dittowill** [comment] 2016-07-21 20:03
im wondering too. i dont see a button to refresh when i put the address on my phone

**Comment by SoonDead** [comment] 2016-07-22 07:27
I seem to have created an issue #117 which is more or less a duplicate of this with the addition of initiating a coordinate change.

**Closed** 2016-08-16 16:03 UTC
